
package rs.itcentar.katalog_proizvoda;

public class AddProizvodiPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddUserPanel
     */
    public AddProizvodiPanel() {
        initComponents();
    }

    public Proizvodi getProizvodi() {

        return new Proizvodi(tfOpisProizvoda.getText(), tfProizvod.getText(), Double.valueOf(tfCena.getText()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfOpisProizvoda = new javax.swing.JTextField();
        labelImeProizvoda = new javax.swing.JLabel();
        labelOpisProizvoda = new javax.swing.JLabel();
        tfProizvod = new javax.swing.JTextField();
        labelCena = new javax.swing.JLabel();
        tfCena = new javax.swing.JTextField();

        labelImeProizvoda.setText("Ime proizvoda");

        labelOpisProizvoda.setText("Opis proizvoda");

        labelCena.setText("Cena");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImeProizvoda)
                    .addComponent(labelOpisProizvoda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCena, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(tfOpisProizvoda)
                    .addComponent(tfProizvod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImeProizvoda)
                    .addComponent(tfProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOpisProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOpisProizvoda))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCena)
                    .addComponent(tfCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCena;
    private javax.swing.JLabel labelImeProizvoda;
    private javax.swing.JLabel labelOpisProizvoda;
    private javax.swing.JTextField tfCena;
    private javax.swing.JTextField tfOpisProizvoda;
    private javax.swing.JTextField tfProizvod;
    // End of variables declaration//GEN-END:variables
}
